
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 23 20:18:36 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 51;
  public static final int CONST = 6;
  public static final int SLASH = 33;
  public static final int LPAREN = 42;
  public static final int SEMI = 38;
  public static final int CONTINUE = 21;
  public static final int LSS = 26;
  public static final int MINUS = 31;
  public static final int STAR = 32;
  public static final int RPAREN = 43;
  public static final int AND = 28;
  public static final int RECORD = 3;
  public static final int OR = 29;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int INC = 36;
  public static final int GEQ = 25;
  public static final int PLUS = 30;
  public static final int IF = 16;
  public static final int THIS = 12;
  public static final int DOT = 41;
  public static final int BOOLEAN = 50;
  public static final int EOF = 0;
  public static final int LSBRACE = 44;
  public static final int RETURN = 20;
  public static final int GTR = 24;
  public static final int EQUAL = 35;
  public static final int RSBRACE = 45;
  public static final int SUPER = 13;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PERCENT = 34;
  public static final int NUMBER = 48;
  public static final int NEQ = 23;
  public static final int IDENT = 49;
  public static final int BREAK = 15;
  public static final int VOID = 10;
  public static final int EQU = 22;
  public static final int COLON = 39;
  public static final int LBRACE = 46;
  public static final int ELSE = 17;
  public static final int ENUM = 5;
  public static final int READ = 9;
  public static final int GOTO = 14;
  public static final int WHILE = 19;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 11;
  public static final int PROG = 2;
  public static final int LEQ = 27;
  public static final int DEC = 37;
  public static final int PRINT = 8;
  public static final int DO = 18;
}

